### ISSUE TITLE
HDMI->VGA convertes for the speakers

### ISSUE THREAD

**Issue by krokodilerian** [FOSDEM/video#27]
As VGA was officially deprecated last year, and half the laptops on the market already don't have VGA but HDMI, we need to offer HDMI port for the speakers (as "bring VGA" is a bit hard already). The current easy option is to source 25 such converters and have in each room one + hdmi cable, and tell the speakers that these are their options, and if they have something weird, they need to bring a converter from it.

**Comment by RichiH** [comment]
Also tell devrooms to bring extra if they expect people to lack either.

Richard

Sent by mobile; excuse my brevity.

**Comment by markvdb** [comment]
Gerry or Michael, can you please place an order for the following:

* http://www.tme.eu/en/details/cv0058/hdmi-dvi-displayport-cables-and-adapt/logilink/ (25 pcs)
* http://www.tme.eu/en/details/hdmi.he010.020/hdmi-dvi-displayport-cables-and-adapt/goobay/51820/ (50 pcs)

Maybe best order the hdmi cabes and the hdmi->vga adapters they have in stock first, then separately order the leftover hdmi->vga adapters?

(Gerry, only assigning you because I can't add Michael here. Feel free to kick it on to him of course!)

**Comment by markvdb** [comment]
Just getting one already for next weekend's hackathon would be really useful!

**Comment by krokodilerian** [comment]
Tested at the hackathon, worked well.

**Comment by gerryd** [comment]
I have ordered what was available at TME. We will have 11 HDMI to VGA converters and 50 HDMI cables available.
