### ISSUE TITLE
update preroll, background and postroll artwork for 2017

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#51]
We will need updated preroll and postroll artwork for 2017. Mostly update the sponsors.

Aghos, I've taken the liberty of throwing this at you, as contacts with the graphics people go through you iirc. Feel free to reassign to me if I remember wrongly.

The artwork from last year is in https://github.com/FOSDEM/videobox/tree/master/venc/artwork . Bitmap only, although the fonts used are there. I could contact Niels to try and get svg sources if that helps. If so, let me know...

**Comment by gerryd** [comment]
I have the source file for the background image if need be. These were made by David, if you need the source file for the sponsors, I can get that as well.

Now that we are talking about pre- and postroll artwork, I'd like to suggest some changes and raise some questions:
- Could we do a fade in/out between the pre-roll, video and post-roll? (this is for the video team, not the artwork team)
- We should add some animation to either the pre- or post-roll (or both)
- Could we have the title of the presentation and the copyright notice in the pre-roll? And perhaps not show any text during the video?
- Last edition, it seems the artwork wasn't used the way it was meant to, the logo looks off-centered during the presentation and it all looks somewhat messy. Could we have specs upfront of the different scenes we will be using and have matching artwork?
- How will we handle slides-only and cam-only presentations? Should the artwork be different for both?

**Comment by markvdb** [comment]
* Fade in/out: It depends on what you mean with that. A white sheet for about a second, as Niels had implemented for 2015 would look much better indeed than jumping directly from still slide to video. Fade effects? Wishlist if you ask me.
* Animation in pre- or postroll? Deep into wishlist territory if you ask me, but not inherently hard.
* Presentation and copyright notice in pre- or postroll should be perfectly feasible.
* No text during the video was the idea since the beginning. Good that is being made explicit. Any other option would make cutting without reencoding impossible.
* We need a universal background image for all scenes.

**Comment by markvdb** [comment]
@gerryd , can you send me the source files for this, or send them directly to @aghos  and Egbert. We need to get this rolling again...

Making sure this gets done should be a task for @yoe really, but let's not wait for that...

**Comment by yoe** [comment]
Animation is currently hard, because I use an SVG file, not a video, to create preroll/postroll videos. The advantage of this is that generating the preroll per talk is trivial (just run s/@SPEAKERS@/<speaker names from database>/g over the SVG file, run inkscape --export-png=, take the png file and turn it into a video), but adding animations to that is not feasible.

Fade could be done if someone knows an ffmpeg command line to do it ;-)

If we really need an animation, I suggest we add it to the postroll video, where the sponsor logos would sit and which would not need to be customized per video. I can then have a static postroll video that I use for every talk.

This is yoe/sreview#6, BTW

**Comment by krokodilerian** [comment]
Was done and is in yoe/sreview#6.
