### ISSUE TITLE
large black borders on some videos

### ISSUE THREAD

**Issue by johanvdw** [FOSDEM/video#90]
Some videos show scaling issues, eg:
http://ftp.fau.de/fosdem/2017/H.2214/graph_analytics_massively_parallel_processing_databases.mp4

in the same room it went good with another one:
http://ftp.heanet.ie/mirrors/fosdem-video/2017/H.2214/graph_drupal_cms_neo4j.mp4

other issue:
http://bofh.nikhef.nl/events/FOSDEM/2017/H.2214/graph_incremental_queries_open_cypher.mp4

In all these cases the projector seemed to be doing the right thing.

I wonder if we can do something about this.

**Comment by krokodilerian** [comment]
@johanvdw , it's a known issue which doesn't seem to have a good solution except a rework of the boxes, or make the devroom managers specifically check if the output on the box's display looks right. The whole thing comes from having VGA negotiation with two different devices on the same port, and seems like some devices don't handle this well.

There are some future plans to fix this in videobox v2, by giving the projector the same input we use for the encoder, instead of splitting the input signal from the end user.

**Comment by markvdb** [comment]
Slides boxes are going HDMI only. We also have better control of the scalers through the infrafred remote hack. This ticket has become irrelevant.
