### ISSUE TITLE
nginx-rtmp: record directly to mp4 container

### ISSUE THREAD

**Issue by markvdb** [FOSDEM/video#99]
Asked nginx rtmp author to allow recording to mp4 instead of flv. Hopefully also with indexing.

https://github.com/arut/nginx-rtmp-module/issues/957

**Comment by yoe** [comment]
> Hopefully also with indexing.

How would he do that though? if you want an indexed MP4 with a MOOV atom, by definition you need all data. If you're recording, by definition you don't have all data...

**Comment by mixcomp** [comment]
@yoe @markvdb wowza has built-in live mp4 recording for ages since more than 5 years ago. Why is it so hard for nginx-rtmp? I don't understand. mp4 is like a very basic need. flv won't play on any browser today. I don't see any benefit in recording in a non standard format.

I am also on the lookout for this...please let me know if there is any way to do this. I left my wowza subscription believing that everything was possible with nginx rtmp....

**Comment by ingen0s** [comment]
Hello - though it is a bit more server load - perhaps use ffmpeg to do that for you.

**Comment by markvdb** [comment]
@ingen0s We already do it that way. On every completed recording, we get an flv, then a few seconds later an mp4.

**Comment by krokodilerian** [comment]
nginx-rtmp is getting replaced will VLC.

**Comment by akashjakhad** [comment]
you can try in nginx conf
exec_push ffmpeg -i "rtmp://localhost:1935/src/$name" -vcodec libx264 -acodec aac -f mp4 "/tmp/rec/$name.mp4"
